# Generated by Django 3.1.7 on 2021-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Femaleness', models.BooleanField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Come_to', models.ManyToManyField(to='Organiser.Event')),
            ],
        ),
    ]
