# Generated by Django 3.1.7 on 2021-02-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0003_student1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
