# Generated by Django 3.1.7 on 2021-02-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser', '0008_auto_20210227_1149'),
        ('Public', '0004_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student',
        ),
    ]
