# Generated by Django 3.1.7 on 2021-03-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0006_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='notset', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
