# Generated by Django 3.1.7 on 2021-02-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser', '0003_event1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
