# Generated by Django 3.1.7 on 2021-02-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
        ('Organiser', '0004_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event1',
            new_name='Event',
        ),
    ]
