# Generated by Django 3.1.7 on 2021-02-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser', '0005_auto_20210227_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Femaleness', models.BooleanField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Come_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organiser.event')),
            ],
        ),
    ]
