# Generated by Django 3.1.7 on 2021-02-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser', '0007_delete_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest1',
            new_name='Guest',
        ),
    ]
