# Generated by Django 3.1.7 on 2021-02-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser', '0009_auto_20210227_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Last_name',
            new_name='Last_Name',
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('First_Name', 'Last_Name', 'Attending')},
        ),
    ]
