# Generated by Django 3.1.7 on 2021-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=12)),
                ('Category', models.CharField(max_length=30)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
